### ISSUE TITLE
Trouble using pose tracking functionality

### ISSUE THREAD

**Issue by IvoD1998** [FAU-FAPS/adaptive_motion_control#2]
Hello

I am trying to use the pose tracking functionality of the adaptive motion middleware to follow an object that is found by my camera (eye-in-hand setup). 
From my object detection, I am receiving a pose which I would like to follow with the camera frame from my robot chain. 
I have tried to pass the pose data relative to the camera frame and change the ROS parameters to set the base and tool frames accordingly, but this does not seem to work the way I expected. 
I also tried transforming the pose data to the base_link of the robot and only setting the tcp_frame, but this also does not yield the desired outcome.

Am I misusing or misunderstanding the pose tracking feature?
Do you have any idea how I could resolve this?

Thank you in advance!

**Comment by enginkarlidag** [comment]
Hello,

if I did understand correctly what you are trying to accomplish then it should be possible. But it seems there was a misunderstanding of how the pose tracking works and what the parameters are for.

> From my object detection, I am receiving a pose which I would like to follow with the camera frame from my robot chain. I have tried to pass the pose data relative to the camera frame and change the ROS parameters to set the base and tool frames accordingly, but this does not seem to work the way I expected.

Well, just for clarification: On the robot controller the velocity control (which is used in pose tracking) moves the tool of the robot (usually `tool0`) with respect to the base frame (usually `base` or `base_link`). These two represent the standard frames of the robot vendor. Please refer to the [example config file](https://github.com/FAU-FAPS/adaptive_motion_control/blob/main/robot_middleware/config/settings_example.yaml) for more information on the parameters. So you shouldn't change the base and tool frame parameters unless you have a custom URDF with non-standard link names (e.g. with a prefix). In other words, all transformations between frames must be computed on the ROS side before the velocity commands are sent to the robot.

> I also tried transforming the pose data to the base_link of the robot and only setting the tcp_frame, but this also does not yield the desired outcome.

The pose tracking subscribes to a `PoseStamped` message where you also have the `header.frame_id`. This frame will be used to transform the goal pose back to the base frame specified in the parameters. If the `frame_id` in the header is empty then the base frame will be assumed as the reference frame with a warning which is only printed once. In your case it is a good idea to transform the goal pose to the base frame before publishing it because the camera frame has not a static transform to the base frame. Also note, in the `robot_middleware` only the transforms known in the robot model (URDF) are taken into account. So `tf` is not used to lookup transforms. These kind of transforms must also be computed externally.

Finally, the `tcp_frame` parameter is unfortunately not implemented yet (see the description in the config file linked above). That means, that right now it's only possible to move the `tool0` of the robot to a goal pose. This is what we used in our project to teleoperate the robot. As a workaround, if you want to move a custom TCP (here your camera frame?) via pose tracking then you must calculate backwards the goal pose for `tool0`. So when you get a goal pose for your camera frame you have to apply the static transform between `camera_frame->tool0`.

I hope this helps!

**Comment by IvoD1998** [comment]
Hello
Thank you! I indeed read over the fact that the TCP_frame parameter is not yet implemented. 
By manually calculating the required flange pose, the pose tracking works as expected.
